CREATE TABLE Files (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  size BIGINT NOT NULL,
  totalChunks INTEGER NOT NULL,
  uploadedChunks INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE Chunks (
  id VARCHAR(255) PRIMARY KEY,
  fileId INTEGER NOT NULL REFERENCES Files(id),
  chunkNumber INTEGER NOT NULL
);